[tool.poetry]
name = "json-kit"
version = "0.1.0"
description = "One man's attempt to conquer JSON once and for all"
authors = ["Tyler Fisher <tylerfisher@tylerfisher.ca>"]
license = "MIT"
readme = "README.md"
packages = [{include = "json_kit"}]

[tool.poetry.dependencies]
python = "^3.10"
genson = "^1.2.2"
networkx = "^3.1"
click = "^8.1.3"
matplotlib = "^3.7.1"
pydot = "^1.4.2"

[tool.poetry.scripts]
json2dot = "json_kit.cli.json2dot:main"
json2img = "json_kit.cli.json2img:main"
json2schema = "json_kit.cli.json2jsonschema:main"
json2jsonschema = "json_kit.cli.json2jsonschema:main"
jsonschema2dot = "json_kit.cli.jsonschema2dot:main"
jsonschema2img = "json_kit.cli.jsonschema2img:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
